import XCTest
@testable import RepCoachCore

/// Expected values are generated by docs/engine_reference.py. If a rule changes, change the
/// Python reference first, re-run it, then update these numbers.
final class ProgressionEngineTests: XCTestCase {

    let p = Prescription(sets: 3, repMin: 8, repMax: 12, increment: 2.5)
    let pullUp = Prescription(sets: 5, repMin: 3, repMax: 5, increment: 2.5, sessionsAtTopToProgress: 2)
    let legPress = Prescription(sets: 4, repMin: 8, repMax: 12, increment: 10)
    let lateral = Prescription(sets: 3, repMin: 15, repMax: 20, increment: 1)

    func s(_ pairs: [(Double, Int)]) -> [LoggedSet] { pairs.map { LoggedSet(weight: $0.0, reps: $0.1) } }
    func same(_ w: Double, _ r: Int, _ n: Int) -> [LoggedSet] { Array(repeating: LoggedSet(weight: w, reps: r), count: n) }

    // MARK: firstTarget

    func testNoHistoryAsksForWeight() {
        XCTAssertEqual(ProgressionEngine.firstTarget(for: p, history: []),
                       SessionTarget(weight: nil, sets: 3, reason: .firstTime))
    }

    func testAllSetsAtTopIncreases() {
        XCTAssertEqual(ProgressionEngine.firstTarget(for: p, history: [same(20, 12, 3)]),
                       SessionTarget(weight: 22.5, sets: 3, reason: .increase))
    }

    func testInRangeRepeats() {
        XCTAssertEqual(ProgressionEngine.firstTarget(for: p, history: [s([(20, 12), (20, 11), (20, 10)])]),
                       SessionTarget(weight: 20, sets: 3, reason: .repeatWeight))
    }

    func testPullUpNeedsTwoSessionsAtTop() {
        let history = [same(15, 5, 5), s([(15, 5), (15, 4), (15, 4), (15, 4), (15, 3)])]
        XCTAssertEqual(ProgressionEngine.firstTarget(for: pullUp, history: history),
                       SessionTarget(weight: 15, sets: 5, reason: .repeatWeight))
    }

    func testPullUpTwoSessionsAtTopIncreases() {
        XCTAssertEqual(ProgressionEngine.firstTarget(for: pullUp, history: [same(15, 5, 5), same(15, 5, 5)]),
                       SessionTarget(weight: 17.5, sets: 5, reason: .increase))
    }

    func testTwoMissedSessionsDecrease() {
        let history = [s([(20, 7), (20, 6), (17.5, 8)]), s([(20, 8), (20, 7), (20, 7)])]
        XCTAssertEqual(ProgressionEngine.firstTarget(for: p, history: history),
                       SessionTarget(weight: 17.5, sets: 3, reason: .decrease))
    }

    func testOneMissedSessionRepeats() {
        let history = [same(20, 7, 1) + same(20, 6, 2), s([(20, 10), (20, 9), (20, 8)])]
        XCTAssertEqual(ProgressionEngine.firstTarget(for: p, history: history),
                       SessionTarget(weight: 20, sets: 3, reason: .repeatWeight))
    }

    func testLegPressTwoMissesDropsOneIncrement() {
        XCTAssertEqual(ProgressionEngine.firstTarget(for: legPress, history: [same(100, 7, 4), same(100, 6, 4)]),
                       SessionTarget(weight: 90, sets: 4, reason: .decrease))
    }

    func testDeloadLightensAndHalvesSets() {
        XCTAssertEqual(ProgressionEngine.firstTarget(for: p, history: [same(20, 10, 3)], deload: true),
                       SessionTarget(weight: 17.5, sets: 2, reason: .deload))
        XCTAssertEqual(ProgressionEngine.firstTarget(for: legPress, history: [same(100, 10, 4)], deload: true),
                       SessionTarget(weight: 90, sets: 2, reason: .deload))
    }

    // MARK: firstTarget after a weight change within the session

    func testARaiseMidSessionCarriesToNextTime() {
        XCTAssertEqual(ProgressionEngine.firstTarget(for: p, history: [s([(20, 15), (22.5, 12), (22.5, 11)])]),
                       SessionTarget(weight: 22.5, sets: 3, reason: .repeatWeight))
    }

    func testARaisedSessionAtTheTopIncreasesFromTheRaise() {
        XCTAssertEqual(ProgressionEngine.firstTarget(for: p, history: [s([(20, 15), (22.5, 12), (22.5, 12)])]),
                       SessionTarget(weight: 25, sets: 3, reason: .increase))
    }

    func testAHeavierAttemptThatFellShortIsNotAMiss() {
        XCTAssertEqual(ProgressionEngine.firstTarget(for: p, history: [s([(20, 12), (20, 12), (22.5, 4)])]),
                       SessionTarget(weight: 20, sets: 3, reason: .repeatWeight))
    }

    func testDroppingAfterTheFirstSetIsNotTheTop() {
        XCTAssertEqual(ProgressionEngine.firstTarget(for: p, history: [s([(20, 12), (17.5, 12), (17.5, 12)])]),
                       SessionTarget(weight: 20, sets: 3, reason: .repeatWeight))
    }

    func testARaiseThatFellShortGoesBackToTheFirstWeight() {
        XCTAssertEqual(ProgressionEngine.firstTarget(for: p, history: [s([(20, 15), (22.5, 7), (22.5, 7)])]),
                       SessionTarget(weight: 20, sets: 3, reason: .repeatWeight))
    }

    func testWorkingWeight() {
        XCTAssertEqual(ProgressionEngine.workingWeight(s([(20, 15), (22.5, 12), (22.5, 11)]), p: p), 22.5)
        XCTAssertEqual(ProgressionEngine.workingWeight(s([(20, 12), (20, 12), (22.5, 4)]), p: p), 20)
        XCTAssertEqual(ProgressionEngine.workingWeight(s([(22.5, 5), (20, 8), (20, 7)]), p: p), 22.5)
        XCTAssertNil(ProgressionEngine.workingWeight([], p: p))
    }

    // MARK: nextSet

    func testNextSet() {
        let cases: [(Prescription, Double, Int, Int, Int, NextSetTarget)] = [
            (p, 20, 6, 1, 3, .init(weight: 17.5, reason: .dropWeight)),
            (p, 20, 7, 1, 3, .init(weight: 17.5, reason: .dropWeight)),
            (p, 20, 3, 1, 3, .init(weight: 15, reason: .dropWeight)),
            (p, 20, 10, 1, 3, .init(weight: 20, reason: .keep)),
            (p, 20, 13, 1, 3, .init(weight: 20, reason: .keep)),
            (p, 20, 14, 1, 3, .init(weight: 22.5, reason: .raiseWeight)),
            (p, 20, 15, 1, 3, .init(weight: 22.5, reason: .raiseWeight)),
            (p, 20, 15, 3, 3, .init(weight: 20, reason: .keep)),
            (p, 20, 25, 1, 3, .init(weight: 25, reason: .raiseWeight)),
            (p, 20, 40, 1, 3, .init(weight: 25, reason: .raiseWeight)),
            (legPress, 100, 16, 1, 4, .init(weight: 110, reason: .raiseWeight)),
            (legPress, 100, 5, 2, 4, .init(weight: 80, reason: .dropWeight)),
            (lateral, 8, 12, 1, 3, .init(weight: 6, reason: .dropWeight)),
            (lateral, 8, 22, 1, 3, .init(weight: 9, reason: .raiseWeight)),
            (pullUp, 15, 7, 1, 5, .init(weight: 17.5, reason: .raiseWeight)),
            (pullUp, 0, 8, 1, 5, .init(weight: 2.5, reason: .raiseWeight)),
        ]
        for (pres, w, r, i, n, expected) in cases {
            XCTAssertEqual(ProgressionEngine.nextSet(for: pres, weight: w, reps: r, setIndex: i, totalSets: n), expected,
                           "w \(w) r \(r) set \(i)/\(n)")
        }
    }

    // MARK: Pull-up volume and charts

    func testVolumeReps() {
        XCTAssertEqual(ProgressionEngine.volumeReps(amrap: 12), 7)
        XCTAssertEqual(ProgressionEngine.volumeReps(amrap: 9), 5)
        XCTAssertEqual(ProgressionEngine.volumeReps(amrap: 13), 8)
        XCTAssertEqual(ProgressionEngine.volumeReps(amrap: 1), 1)
    }

    func testEstimated1RM() {
        XCTAssertEqual(ProgressionEngine.estimated1RM(weight: 20, reps: 10), 26.67, accuracy: 0.001)
    }

    // MARK: reps and timed kinds

    func testReachedTopOfRange() {
        func top(_ reps: [Int], _ top: Int, _ planned: Int) -> Bool {
            ProgressionEngine.reachedTopOfRange(reps.map { LoggedSet(weight: 0, reps: $0) }, top: top, plannedSets: planned)
        }
        XCTAssertTrue(top([12, 12, 12], 12, 3), "every set at the top")
        XCTAssertFalse(top([12, 11, 12], 12, 3), "one set short")
        XCTAssertFalse(top([12, 12], 12, 3), "too few sets")
        XCTAssertTrue(top([46, 45, 50], 45, 3), "timed, past the max")
        XCTAssertTrue(top([15, 15, 15, 9], 15, 3), "extra sets ignored")
    }

    func testRounding() {
        XCTAssertEqual(ProgressionEngine.roundNearest(17, to: 2.5), 17.5)
        XCTAssertEqual(ProgressionEngine.roundNearest(85, to: 10), 90)
        XCTAssertEqual(ProgressionEngine.roundDown(19, to: 2.5), 17.5)
        XCTAssertEqual(ProgressionEngine.roundDown(17.5, to: 2.5), 17.5)
    }

    // MARK: Ramp-up sets

    /// The "ramp-up:" lines printed by docs/engine_reference.py.
    func testRampUpVectors() {
        func ramp(_ working: Double?, _ inc: Double, _ repMax: Int, _ role: RampUpRole,
                  _ setting: RampUpSetting = .mainLifts, bodyweight: Bool = false) -> [LoggedSet] {
            ProgressionEngine.rampUps(working: working, increment: inc, repMax: repMax, role: role, setting: setting,
                                      bodyweightBase: bodyweight)
                .map { LoggedSet(weight: $0.weight, reps: $0.reps) }
        }
        XCTAssertEqual(ramp(22.5, 2.5, 10, .first), s([(10, 8), (15, 4)]), "Incline DB Press 22.5, first")
        XCTAssertEqual(ramp(20, 2.5, 12, .first), s([(10, 8), (15, 4)]), "20 kg x 12 case, first")
        XCTAssertEqual(ramp(45, 5, 10, .main), s([(30, 5)]), "Machine Chest Press 45, main")
        XCTAssertEqual(ramp(17.5, 2.5, 10, .main), s([(10, 5)]), "Seated DB Shoulder Press 17.5, main")
        XCTAssertEqual(ramp(120, 10, 12, .first), s([(60, 8), (90, 4)]), "Leg Press 120, first")
        XCTAssertEqual(ramp(40, 10, 12, .first), s([(20, 8), (30, 4)]), "Leg Press 40, first")
        XCTAssertEqual(ramp(20, 10, 12, .first), s([(10, 8)]), "Leg Press 20, first (second equals first: left out)")
        XCTAssertEqual(ramp(10, 10, 12, .first), [], "Leg Press 10, first (rounds to zero: none)")
        XCTAssertEqual(ramp(60, 5, 12, .main), s([(40, 5)]), "Hip Thrust 60 inc 5, main")
        XCTAssertEqual(ramp(5, 2.5, 10, .first), s([(2.5, 8)]), "DB 5 kg, first")
        XCTAssertEqual(ramp(2.5, 2.5, 10, .main), [], "DB 2.5 kg, main (rounds to zero)")
        XCTAssertEqual(ramp(7.5, 2.5, 15, .small), [], "Cable Lateral Raise 7.5, small, setting main")
        XCTAssertEqual(ramp(7.5, 2.5, 15, .small, .everyWeightedLift), s([(5, 5)]),
                       "Cable Lateral Raise 7.5, small, setting all")
        XCTAssertEqual(ramp(6, 1, 20, .small, .everyWeightedLift), s([(4, 5)]), "DB Lateral Raise 6 inc 1, small, all")
        XCTAssertEqual(ramp(22.5, 2.5, 10, .first, .off), [], "Incline DB Press 22.5, first, setting off")
        XCTAssertEqual(ramp(nil, 2.5, 10, .first), [], "First time (no working weight)")
        XCTAssertEqual(ramp(20, 2.5, 10, .first), s([(10, 8), (15, 4)]), "Deload week, worked out from 20")
        XCTAssertEqual(ramp(15, 2.5, 5, .first, bodyweight: true), s([(0, 5), (7.5, 3)]), "Weighted Pull-ups +15, first")
        XCTAssertEqual(ramp(2.5, 2.5, 5, .first, bodyweight: true), s([(0, 5)]), "+2.5, first (half rounds to zero)")
        XCTAssertEqual(ramp(15, 2.5, 5, .main, bodyweight: true), s([(0, 5)]), "Weighted Pull-ups +15, main")
        XCTAssertEqual(ramp(0, 2.5, 5, .first, bodyweight: true), [], "Weighted Pull-ups bodyweight only, first")
        XCTAssertEqual(ramp(100, 2.5, 5, .first), s([(50, 5), (75, 4)]), "reps capped at the top of the range")
    }

    func testRampUpsOffForNoRoleAndTheSettingDefault() {
        XCTAssertEqual(ProgressionEngine.rampUps(working: 20, increment: 2.5, repMax: 10, role: nil).count, 0)
        XCTAssertEqual(ProgressionEngine.rampUps(working: 20, increment: 2.5, repMax: 10, role: .first).count, 2,
                       "defaults to main lifts")
        XCTAssertEqual(ProgressionEngine.restAfterRampUpSec, 60)
    }

    /// The "Wednesday roles" line printed by docs/engine_reference.py.
    func testRampUpRolesFollowThePlansOrder() throws {
        func item(_ kind: ItemKind, rest: Int? = nil) -> PlanItem {
            PlanItem(name: "x", exerciseId: UUID().uuidString, group: "", kind: kind, restSec: rest)
        }
        let wednesday = [item(.checklist), item(.weighted, rest: 150), item(.weighted, rest: 150),
                         item(.weighted, rest: 150), item(.weighted, rest: 75), item(.reps, rest: 45)]
        XCTAssertEqual((0..<wednesday.count).map { ProgressionEngine.rampUpRole(dayItems: wednesday, index: $0) },
                       [nil, .first, .main, .main, .small, nil])
        XCTAssertEqual(ProgressionEngine.rampUpRole(dayItems: [item(.weighted)], index: 0), .small, "no rest set")

        // The real week: pull-ups lead Monday, the incline press leads Wednesday.
        let plan = try Plan.bundled()
        func role(_ day: String, _ id: String) -> RampUpRole? {
            let items = plan.days.first { $0.key == day }!.items
            return ProgressionEngine.rampUpRole(dayItems: items, index: items.firstIndex { $0.exerciseId == id }!)
        }
        XCTAssertEqual(role("monday", "weighted-pull-ups"), .first)
        XCTAssertEqual(role("monday", "chest-supported-db-row"), .main)
        XCTAssertEqual(role("wednesday", "incline-db-press"), .first)
        XCTAssertEqual(role("wednesday", "machine-chest-press"), .main)
    }

    func testRampUpSettingStoresStableStrings() throws {
        XCTAssertEqual(RampUpSetting.allCases.map(\.rawValue), ["off", "mainLifts", "everyWeightedLift"])
        XCTAssertEqual(RampUpRole.first.rawValue, "first")
        XCTAssertEqual(try JSONDecoder().decode(RampUpSetting.self, from: Data(#""everyWeightedLift""#.utf8)),
                       .everyWeightedLift)
    }
}
