import XCTest
@testable import RepCoachCore

/// Expected values are generated by docs/engine_reference.py. If a rule changes, change the
/// Python reference first, re-run it, then update these numbers.
final class ProgressionEngineTests: XCTestCase {

    let p = Prescription(sets: 3, repMin: 8, repMax: 12, increment: 2.5)
    let pullUp = Prescription(sets: 5, repMin: 3, repMax: 5, increment: 2.5, sessionsAtTopToProgress: 2)
    let legPress = Prescription(sets: 4, repMin: 8, repMax: 12, increment: 10)
    let lateral = Prescription(sets: 3, repMin: 15, repMax: 20, increment: 1)

    func s(_ pairs: [(Double, Int)]) -> [LoggedSet] { pairs.map { LoggedSet(weight: $0.0, reps: $0.1) } }
    func same(_ w: Double, _ r: Int, _ n: Int) -> [LoggedSet] { Array(repeating: LoggedSet(weight: w, reps: r), count: n) }

    // MARK: firstTarget

    func testNoHistoryAsksForWeight() {
        XCTAssertEqual(ProgressionEngine.firstTarget(for: p, history: []),
                       SessionTarget(weight: nil, sets: 3, reason: .firstTime))
    }

    func testAllSetsAtTopIncreases() {
        XCTAssertEqual(ProgressionEngine.firstTarget(for: p, history: [same(20, 12, 3)]),
                       SessionTarget(weight: 22.5, sets: 3, reason: .increase))
    }

    func testInRangeRepeats() {
        XCTAssertEqual(ProgressionEngine.firstTarget(for: p, history: [s([(20, 12), (20, 11), (20, 10)])]),
                       SessionTarget(weight: 20, sets: 3, reason: .repeatWeight))
    }

    func testPullUpNeedsTwoSessionsAtTop() {
        let history = [same(15, 5, 5), s([(15, 5), (15, 4), (15, 4), (15, 4), (15, 3)])]
        XCTAssertEqual(ProgressionEngine.firstTarget(for: pullUp, history: history),
                       SessionTarget(weight: 15, sets: 5, reason: .repeatWeight))
    }

    func testPullUpTwoSessionsAtTopIncreases() {
        XCTAssertEqual(ProgressionEngine.firstTarget(for: pullUp, history: [same(15, 5, 5), same(15, 5, 5)]),
                       SessionTarget(weight: 17.5, sets: 5, reason: .increase))
    }

    func testTwoMissedSessionsDecrease() {
        let history = [s([(20, 7), (20, 6), (17.5, 8)]), s([(20, 8), (20, 7), (20, 7)])]
        XCTAssertEqual(ProgressionEngine.firstTarget(for: p, history: history),
                       SessionTarget(weight: 17.5, sets: 3, reason: .decrease))
    }

    func testOneMissedSessionRepeats() {
        let history = [same(20, 7, 1) + same(20, 6, 2), s([(20, 10), (20, 9), (20, 8)])]
        XCTAssertEqual(ProgressionEngine.firstTarget(for: p, history: history),
                       SessionTarget(weight: 20, sets: 3, reason: .repeatWeight))
    }

    func testLegPressTwoMissesDropsOneIncrement() {
        XCTAssertEqual(ProgressionEngine.firstTarget(for: legPress, history: [same(100, 7, 4), same(100, 6, 4)]),
                       SessionTarget(weight: 90, sets: 4, reason: .decrease))
    }

    func testDeloadLightensAndHalvesSets() {
        XCTAssertEqual(ProgressionEngine.firstTarget(for: p, history: [same(20, 10, 3)], deload: true),
                       SessionTarget(weight: 17.5, sets: 2, reason: .deload))
        XCTAssertEqual(ProgressionEngine.firstTarget(for: legPress, history: [same(100, 10, 4)], deload: true),
                       SessionTarget(weight: 90, sets: 2, reason: .deload))
    }

    // MARK: nextSet

    func testNextSet() {
        let cases: [(Prescription, Double, Int, Int, Int, NextSetTarget)] = [
            (p, 20, 6, 1, 3, .init(weight: 17.5, reason: .dropWeight)),
            (p, 20, 7, 1, 3, .init(weight: 17.5, reason: .dropWeight)),
            (p, 20, 3, 1, 3, .init(weight: 15, reason: .dropWeight)),
            (p, 20, 10, 1, 3, .init(weight: 20, reason: .keep)),
            (p, 20, 15, 1, 3, .init(weight: 22.5, reason: .raiseWeight)),
            (p, 20, 15, 3, 3, .init(weight: 20, reason: .keep)),
            (p, 20, 14, 1, 3, .init(weight: 20, reason: .keep)),
            (lateral, 8, 12, 1, 3, .init(weight: 6, reason: .dropWeight)),
            (legPress, 100, 5, 2, 4, .init(weight: 80, reason: .dropWeight)),
        ]
        for (pres, w, r, i, n, expected) in cases {
            XCTAssertEqual(ProgressionEngine.nextSet(for: pres, weight: w, reps: r, setIndex: i, totalSets: n), expected,
                           "w \(w) r \(r) set \(i)/\(n)")
        }
    }

    // MARK: Pull-up volume and charts

    func testVolumeReps() {
        XCTAssertEqual(ProgressionEngine.volumeReps(amrap: 12), 7)
        XCTAssertEqual(ProgressionEngine.volumeReps(amrap: 9), 5)
        XCTAssertEqual(ProgressionEngine.volumeReps(amrap: 13), 8)
        XCTAssertEqual(ProgressionEngine.volumeReps(amrap: 1), 1)
    }

    func testEstimated1RM() {
        XCTAssertEqual(ProgressionEngine.estimated1RM(weight: 20, reps: 10), 26.67, accuracy: 0.001)
    }

    func testRounding() {
        XCTAssertEqual(ProgressionEngine.roundNearest(17, to: 2.5), 17.5)
        XCTAssertEqual(ProgressionEngine.roundNearest(85, to: 10), 90)
        XCTAssertEqual(ProgressionEngine.roundDown(19, to: 2.5), 17.5)
        XCTAssertEqual(ProgressionEngine.roundDown(17.5, to: 2.5), 17.5)
    }
}
